### ISSUE TITLE
Improve Notary Project website design and user experience

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#370]
To improve the website user experience, I would like to consolidate the ideas to improve the Notary Project website design and content in this list. Let me know if you have further ideas on improving the website experience.

- [ ]    **Improve the landing page design; add an installation section with a terminal effect design** #335 : The new layout design makes the landing page much pretty & professional and show how easy & fast to install Notation CLI on different OS
- [ ]    **Design and implement a video page to list Youtube videos** #278 : It aggregates all important videos in the same page by category so users should be easier to find and learn Notary Project on demand
- [ ]    **Support version control in the docs**: increase accuracy of the docs and avoid outdated information as well as broken links happen #350 
- [ ]    **Add Algolia search to the website**: The built-in search capability makes users much efficient to look for desired content by keywords
- [ ]    **Design and implement the case study page**: It aggregates all case study articles in the same page so new people should be easier to find testimonials and detailed use cases from others
- [ ]    **Redesign the Community page**: Tell users a comprehensive journey of how to be a contributor
- [ ]    **Add a pop-up window on the landing page to tell users how to join the community**: Guide people to join the chat group, so users can be easier to connect with others and be informed in a central place
- [ ]    **Add Broken link check to Netlify CI**: block any invalid links and absolute links usage in the content, avoid broken links

**Comment by PranitPatil03** [comment]
Hello @FeynmanZhou 👋

I have analyzed the new revamp landing page, and after analysis, I have identified the following improvements:

- [ ] **Consider a visual theme** : We have to employ a consistent colour scheme and style for visual presentation 

- [ ] **Improvement on Footer** : The footer currently has a significant amount of empty space. We can enhance the footer by removing the extra space.

- [ ] **The News and blogs section** :The News and Blogs section can be enhanced to improve its visual appeal. Additionally, we should focus on improving the adoption and trust of the section containers.

- [ ] **Strengthen visual hierarchy** : Current design does not have the standard  heading and subheading format. it is necessary to establish standards for headings, fonts, and font sizes. By using clear headings, subheadings and employing contrasting colours or font sizes the user's attention can be directed towards important information.

- [ ] **Image Improvements** :In the current website the all images are not well in standard sizes The Hero image which explains the overall Notary workflow is very small that's the it is not visually correct placed and also the collaboration images also are very small , so images need to improve 

Can you send me the Figma designs for the landing page? If not, can I create a new design for the landing page? It will help improve the website and fix this issues. Additionally, I can also work on designing the case study page and Community page.

And finally, I have a small suggestion can we migrate the current website to Docusaurus? This platform offers numerous benefits and advantages. The ORAS Project in the CNCF is also using Docusaurus (https://github.com/oras-project/oras-www). If this is possible, I will create a new issue to explain this in more detail. I just wanted to hear your thoughts on this.

Thank you 🔥

**Comment by sanjayk0508** [comment]
> To improve the website user experience, I would like to consolidate the ideas to improve the Notary Project website design and content in this list. Let me know if you have further ideas on improving the website experience.
> 
> * [ ]     **Improve the landing page design; add an installation section with a terminal effect design** [Rebased - New Landing page v1 #335](https://github.com/notaryproject/notaryproject.dev/pull/335) : The new layout design makes the landing page much pretty & professional and show how easy & fast to install Notation CLI on different OS
> * [ ]     **Design and implement a video page to list Youtube videos** [Implementing Video-page UI #278](https://github.com/notaryproject/notaryproject.dev/pull/278) : It aggregates all important videos in the same page by category so users should be easier to find and learn Notary Project on demand
> * [ ]     **Add Algolia search to the website**: The built-in search capability makes users much efficient to look for desired content by keywords
> * [ ]     **Support version control in the docs**: increase accuracy of the docs and avoid outdated information as well as broken links happen
> * [ ]     **Design and implement the case study page**: It aggregates all case study articles in the same page so new people should be easier to find testimonials and detailed use cases from others
> * [ ]     **Redesign the Community page**: Tell users a comprehensive journey of how to be a contributor
> * [ ]     **Add a pop-up window on the landing page to tell users how to join the community**: Guide people to join the chat group, so users can be easier to connect with others and be informed in a central place
> * [ ]     **Add Broken link check to Netlify CI**: block any invalid links and absolute links usage in the content, avoid broken links

Certainly, @FeynmanZhou. We can initiate with the PR for `Rebased: New Landing Page`, as discussed. I will also handle the terminal effect in the meantime.

**Comment by ShravaniAK** [comment]
@FeynmanZhou Is this issue still open? if yes then I would like to work on this!
Thank you
