### ISSUE TITLE
Add Google Analytics 4

### ISSUE THREAD

**Issue by nate-double-u** [notaryproject/notaryproject.dev#74]
This as part of a CNCF-wide effort to upgrade project websites to GA4 since Google has deprecated Universal Analytics (UA). For more details, see:
* https://github.com/cncf/techdocs/issues/108, including reference to:
  * A suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

Since [notaryproject.dev](https://notaryproject.dev/) doesn't have any analytics set currently, we can begin with Google Analytics 4 (GA4).

(Edits by @chalin)

### Tasks

- [x] Create a GA4 site tag under the **CNCF Projects** account.
  The new GA4 measurement ID is **`G-64X4HRE9R0`**.
- [x] Set GA4 ID in `config.yaml` - #86
- [x] Configure GA4 website ID ([gtag.js]) through [Netlify snippet injection], "Google Analytics 4 - only in production", just before `</head>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-64X4HRE9R0"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-64X4HRE9R0');
  </script>
  {% endif %}
  ```
- [x] Confirm that the GA4 site tag is receiving events

Other items:

- Revert #86 since we'll be using [Netlify snippet injection] moving forward
- Update Docsy -- see issue-comment below for related items that need to be done first. https://github.com/notaryproject/notaryproject.dev/issues/44

/cc @chalin @caniszczyk 

[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by FeynmanZhou** [comment]
Will @nate-double-u continue to work on this issue?

**Comment by chalin** [comment]
> - Set GA4 ID in `config.yaml`

FYI, we've started promoting, in some cases, setting of the ID as an environment variable via the Netlify console. We can discuss during our next sync if you'd like.

**Comment by chalin** [comment]
> Will @nate-double-u continue to work on this issue?

I'll let @nate-double-u answer.

**Comment by chalin** [comment]
@nate-double-u - we could wrap this up on Tuesday during or after our sync, WDYT?

**Comment by nate-double-u** [comment]
The new GA4 measurement ID is `G-64X4HRE9R0`.

**Comment by nate-double-u** [comment]
Looks like it's not triggering data yet.

**Comment by chalin** [comment]
The GA4 ID isn't being registered: if you look at the site source, you won't find the ID.

The problem is that the version of Docsy is too old, and only works with UA IDs. You'll need to:

- Fix the production build. For details, see https://github.com/notaryproject/notaryproject.dev/pull/82#issuecomment-1309339791. Otherwise, you won't be able to see any future changes on the production server.
- Address #91, since I'm pretty sure that Docsy was having problems recently with "old" versions of Node
- Update Docsy

**Comment by nate-double-u** [comment]
Related: https://github.com/notaryproject/notaryproject.dev/issues/44

**Comment by chalin** [comment]
On another project I found that Docsy was too old as well. There is some value in getting analytics up ASAP. If you'd like to do that here as well, then you can use this PR as an example: https://github.com/dapr/blog/pull/93/files.

**Comment by chalin** [comment]
Actually, now that we have Netlify access, an even simpler setup for GA4 would be via [Netlify snippet injection]. Would you like me to set that up @nate-double-u, or do a walkthrough of such a setup?

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Since Nate is out for the rest of the year, I've setup [Netlify snippet injection] (for details, see the edited opening comment) so that Notary can start 2023 with analytics enabled.

The GA4 web data stream is processing events, as can be seen from the realtime GA panel:

> <img width="734" alt="image" src="https://user-images.githubusercontent.com/4140793/208685760-e1e751ad-f579-4f23-b2e2-d1ef8d2856c8.png">

Closing this issue. I'll follow up with a revert-PR of #86.

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/
